### ISSUE TITLE
Unable to use in combination with route:cache

### ISSUE THREAD

**Issue by BenSampo** [tightenco/nova-releases#1]
The use of closures in the routes file means that it's not possible to take advantage of [route caching](https://laravel.com/docs/5.6/controllers#route-caching).

**Comment by RicardoRamirezR** [comment]
Oh oh. Yep, it can't be used in production if using ```php artisan route:cache```

**Comment by mattstauffer** [comment]
@BenSampo and @RicardoRamirezR sorry for the delay--I've been out of commission for two weeks. Looking at it now
