### ISSUE TITLE
The card in the dashboard wont show, on the new nova release 1.16

### ISSUE THREAD

**Issue by wefixit-tech** [tightenco/nova-releases#3]

**Comment by RicardoRamirezR** [comment]
Workning: Nova 1.0.16 and nova-releases v0.1.2
Not working: Nova 1.0.16 and nova-releases v0.2.0

**Comment by mattstauffer** [comment]
Thanks y'all; taking a look right now to see what broke :)

**Comment by mattstauffer** [comment]
Great! Thanks!
