### ISSUE TITLE
latest release of laravel/framework deprecated Parsedown

### ISSUE THREAD

**Issue by swapnilsarwe** [tightenco/nova-releases#6]
Hello Team,

latest release of laravel/framework deprecated Parsedown. Hence breaking on latest laravel.

**Comment by mattstauffer** [comment]
Crap, you're right. Thanks! We'll take a look

https://github.com/tightenco/nova-releases/blob/master/src/Http/Controllers/ReleasesController.php#L20

**Comment by mattstauffer** [comment]
Tagged: https://github.com/tightenco/nova-releases/releases/tag/v0.2.5
