### ISSUE TITLE
Bug with install nova-releases on laravel 7.6.2

### ISSUE THREAD

**Issue by cloudkserg** [tightenco/nova-releases#7]
Problem 1
    - tightenco/nova-releases v0.2.5 requires kitetail/zttp ^0.6 -> satisfiable by kitetail/zttp[v0.6.0].
    - Conclusion: remove laravel/framework v7.6.2
    - Conclusion: don't install laravel/framework v7.6.2

**Comment by mattstauffer** [comment]
@cloudkserg Thanks! Will take a look at it asap.

**Comment by mattstauffer** [comment]
@cloudkserg I was trying to do a PR to ZTTP to fix this, but I might just release a new version of Nova-Releases that works for Laravel 7+ and uses the Laravel-native HTTP client inspired by ZTTP.

**Comment by mattstauffer** [comment]
@cloudkserg I did a branch for this--I'll spin up a Laravel 7 app with Nova later to test it, but if you want to test it early, you can: change your `composer` to require the package at this version: "dev-mes/use-laravel-http-client"

**Comment by mattstauffer** [comment]
Fixed in https://github.com/tightenco/nova-releases/releases/tag/v1.0.0.
