### ISSUE TITLE
Unable to install with Laravel 8

### ISSUE THREAD

**Issue by ragingdave** [tightenco/nova-releases#8]
On default installation of L8/Nova when trying to include this package I get the following dependency error:
```
 - kitetail/zttp v0.6.0 requires guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - tightenco/nova-releases v0.2.5 requires kitetail/zttp ^0.6 -> satisfiable by kitetail/zttp[v0.6.0].
```

That is of course if you use guzzle already and would like to stay up to date by using v7.

**Comment by mattstauffer** [comment]
@ragingdave Thanks! Will look at this ASAP.

**Comment by mattstauffer** [comment]
@ragingdave Would you mind trying again with tag https://github.com/tightenco/nova-releases/releases/tag/v1.0.0

**Comment by ragingdave** [comment]
Yep! Currently working in a L8 install. Thanks!
